version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - echo "==> Check tool versions"
      - node --version || true
      - npm --version || true
      - docker --version
      - aws --version

  pre_build:
    commands:
      - echo "==> Resolve account & region"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - : "${AWS_DEFAULT_REGION:?AWS_DEFAULT_REGION must be set by CodeBuild}"
      - : "${ECR_REPO:?ECR_REPO must be set}"
      - : "${CONTAINER_NAME:=app}"
      - : "${CONTAINER_PORT:=80}"
      - : "${SYSTEM_NAME:=demo}"
      - : "${ENVIRONMENT:=prod}"
      - : "${TASK_CPU:=256}"
      - : "${TASK_MEMORY:=512}"
      - IMAGE_REPO="${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/${ECR_REPO}"
      - IMAGE_TAG="${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}"
      - IMAGE_URI="${IMAGE_REPO}:${IMAGE_TAG}"
      - echo "==> Login to ECR"
      - aws ecr get-login-password | docker login --username AWS --password-stdin "${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"

  build:
    commands:
      - echo "==> Build Angular (adjust if your project path differs)"
      - npm ci
      - npm run build
      - echo "==> Docker build & push"
      - docker build -t "${IMAGE_URI}" -t "${IMAGE_REPO}:latest" .
      - docker push "${IMAGE_URI}"
      - docker push "${IMAGE_REPO}:latest"

      - echo "==> Generate taskdef.json"
      - EXEC_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${SYSTEM_NAME}-${ENVIRONMENT}-ecsTaskExecutionRole"
      - TASK_ROLE_ARN="arn:aws:iam::${ACCOUNT_ID}:role/${SYSTEM_NAME}-${ENVIRONMENT}-ecsTaskRole"
      - LOG_GROUP="/ecs/${SYSTEM_NAME}-${ENVIRONMENT}"
      - |
        cat > taskdef.json <<'JSON'
        {
          "family": "__FAMILY__",
          "networkMode": "awsvpc",
          "requiresCompatibilities": ["FARGATE"],
          "cpu": "__CPU__",
          "memory": "__MEM__",
          "executionRoleArn": "__EXEC_ROLE__",
          "taskRoleArn": "__TASK_ROLE__",
          "containerDefinitions": [
            {
              "name": "__CONTAINER_NAME__",
              "image": "__IMAGE_URI__",
              "portMappings": [
                { "containerPort": __CONTAINER_PORT__, "protocol": "tcp" }
              ],
              "essential": true,
              "logConfiguration": {
                "logDriver": "awslogs",
                "options": {
                  "awslogs-group": "__LOG_GROUP__",
                  "awslogs-region": "__REGION__",
                  "awslogs-stream-prefix": "app"
                }
              },
              "healthCheck": {
                "retries": 3,
                "command": ["CMD-SHELL", "curl -f http://localhost:__CONTAINER_PORT__/ || exit 1"],
                "timeout": 5,
                "interval": 10,
                "startPeriod": 10
              }
            }
          ]
        }
        JSON
      - |
        sed -i \
          -e "s@__FAMILY__@${SYSTEM_NAME}-${ENVIRONMENT}-task@g" \
          -e "s@__CPU__@${TASK_CPU}@g" \
          -e "s@__MEM__@${TASK_MEMORY}@g" \
          -e "s@__EXEC_ROLE__@${EXEC_ROLE_ARN}@g" \
          -e "s@__TASK_ROLE__@${TASK_ROLE_ARN}@g" \
          -e "s@__CONTAINER_NAME__@${CONTAINER_NAME}@g" \
          -e "s@__IMAGE_URI__@${IMAGE_URI}@g" \
          -e "s@__CONTAINER_PORT__@${CONTAINER_PORT}@g" \
          -e "s@__LOG_GROUP__@${LOG_GROUP}@g" \
          -e "s@__REGION__@${AWS_DEFAULT_REGION}@g" \
          taskdef.json

      - echo "==> Generate appspec.yaml (CodeDeploy for ECS)"
      - |
        cat > appspec.yaml <<'YAML'
        version: 1.0
        Resources:
          - TargetService:
              Type: AWS::ECS::Service
              Properties:
                TaskDefinition: taskdef.json
                LoadBalancerInfo:
                  ContainerName: __CONTAINER_NAME__
                  ContainerPort: __CONTAINER_PORT__
                PlatformVersion: "1.4.0"
        YAML
      - |
        sed -i \
          -e "s@__CONTAINER_NAME__@${CONTAINER_NAME}@g" \
          -e "s@__CONTAINER_PORT__@${CONTAINER_PORT}@g" \
          appspec.yaml

artifacts:
  files:
    - taskdef.json
    - appspec.yaml
    - '**/*'
  discard-paths: no
