version: 0.2

env:
  variables:
    # Angularのdistディレクトリ（Dockerfile ARG と合わせておくと便利）
    DIST_DIR: "dist/demo-multipage/browser"
    CONTAINER_NAME: "app"
    CONTAINER_PORT: "80"
    HEALTHCHECK_PATH: "/healthz"

phases:
  install:
    commands:
      - echo "Node/npm versions"
      - node --version || true
      - npm --version || true

  pre_build:
    commands:
      - echo "Login to ECR"
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGION=${AWS_DEFAULT_REGION}
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com
      - IMAGE_URI=${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${ECR_REPO}
      - echo "IMAGE_URI=$IMAGE_URI"

  build:
    commands:
      - echo "Install deps & Angular build"
      - npm ci
      - npm run build
      # Angular 18 出力は dist/<project>/browser/ 想定。環境に応じてDIST_DIRを合わせる
      - test -d "${DIST_DIR}" || (echo "dist not found: ${DIST_DIR}" && ls -la dist && exit 1)

      - echo "Docker build & push"
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - docker build --build-arg DIST_DIR="${DIST_DIR}" -t ${IMAGE_URI}:${IMAGE_TAG} -t ${IMAGE_URI}:latest .
      - docker push ${IMAGE_URI}:${IMAGE_TAG}
      - docker push ${IMAGE_URI}:latest

      # CodeDeploy(ECS) 用に TaskDef/AppSpec を生成
      - printf '[{"name":"%s","imageUri":"%s:%s"}]' "$CONTAINER_NAME" "$IMAGE_URI" "$IMAGE_TAG" > imagedefinitions.json
      - sed "s@{{IMAGE_URI}}@${IMAGE_URI}:${IMAGE_TAG}@g" deploy/taskdef.json.tpl > taskdef.json
      - cp deploy/appspec.yaml .

artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yaml
    - '**/*'
  discard-paths: no
